import com.vanniktech.maven.publish.DeploymentValidation

plugins {
    id 'groovy'
    id 'maven-publish'
    id 'signing'
    id 'com.vanniktech.maven.publish' version '0.37.0'
}

targetCompatibility = 1.8
sourceCompatibility = 1.8

group = 'com.github.chubbard'
version = '1.2.0-SNAPSHOT'
description = """
A lightweight standalone ETL engine for groovy.  Gratum is groovy + datum.
"""

repositories {
    mavenCentral()
}

dependencies {
    implementation group: 'commons-io', name: 'commons-io', version: '2.18.0'
    implementation group: 'commons-codec', name: 'commons-codec', version: '1.15'
    implementation group: 'commons-cli', name: 'commons-cli', version: '1.4'


    implementation(platform("org.apache.groovy:groovy-bom:4.0.33"))
    implementation('org.apache.groovy:groovy')
    implementation('org.apache.groovy:groovy-json')
    implementation('org.apache.groovy:groovy-xml')
    implementation('org.apache.groovy:groovy-sql')

    implementation(platform("com.squareup.okhttp3:okhttp-bom:4.12.0"))
    implementation("com.squareup.okhttp3:okhttp")
    implementation("com.squareup.okhttp3:logging-interceptor")

//    implementation 'org.apache.poi:poi:5.2.2'
//    implementation 'org.apache.poi:poi-ooxml:5.2.2'
//    implementation 'org.apache.poi:poi-ooxml-lite:5.2.2'
    implementation 'org.apache.poi:poi:4.1.2'
    implementation 'org.apache.poi:poi-ooxml:4.1.2'
    implementation 'org.apache.poi:ooxml-schemas:1.4'
    implementation group: "org.apache.commons", name:"commons-compress", version:"1.27.1"
    implementation group: "com.jcraft", name: "jsch", version: "0.1.55"
    implementation "org.bouncycastle:bcprov-jdk18on:1.80",
            "org.bouncycastle:bcpg-jdk18on:1.80",
            "org.bouncycastle:bcpkix-jdk18on:1.80"

    implementation("org.slf4j:slf4j-api:2.0.16")
    testRuntimeOnly("org.slf4j:slf4j-jdk14:2.0.16")
    testImplementation("com.h2database:h2:2.4.240")

//    testCompile "mysql:mysql-connector-java:5.1.40"
//    testImplementation group: 'junit', name: 'junit', version: '4.13.2'
    testImplementation 'org.junit.jupiter:junit-jupiter-api:5.9.1'
    testImplementation 'org.junit.jupiter:junit-jupiter-engine:5.9.1'
}

tasks.register('groovydocJar', Jar) {
    dependsOn groovydoc
    archiveClassifier = 'groovydoc'
    from groovydoc.destinationDir
}

tasks.register('sourcesJar', Jar) {
    archiveClassifier = 'sources'
    from sourceSets.main.allSource
}

mavenPublishing {
//    coordinates(group, "gratum", version)SonatypeHost.CENTRAL_PORTAL

    // Configures your staging target explicitly for the modern Sonatype Central framework
    publishToMavenCentral()

    // Automatically handles GPG signing when you run publish tasks
    signAllPublications()

    pom {
        name = project.name
        description = project.description
        url = 'https://github.com'
        licenses {
            license {
                name = "The Apache License, Version 2.0"
                url = "http://apache.org"
            }
        }
        developers {
            developer {
                id = "chubbard"
                name = "Charlie Hubbard"
                email = "gratum@fuseanalytics.com"
            }
        }
        scm {
            connection = "scm:https://github.com.git"
            developerConnection = "scm:https://github.com.git"
            url = "https://github.com.git"
        }
    }
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            artifact groovydocJar
            artifact sourcesJar
            //artifact javadocJar
        }
    }
}

tasks.withType(PublishToMavenRepository).configureEach {
    dependsOn(tasks.withType(Sign))
}

test { useJUnitPlatform() }

tasks.named('wrapper') {
    gradleVersion = '8.14.5'
}
